### ISSUE TITLE
CLI for all core-infrastructure products: setup for single-product CLIs

### ISSUE THREAD

**Issue by rose-coste** [rackerlabs/docs-core-infra-user-guide#106]
at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/index.html, 
rewrite to set expectation of different CLIs for each product

in linked-to pages, change section titles to eliminate "rax-cli" references"

**Comment by rtgoodwin** [comment]
# Cloud Images:
* client is "python-glanceclient". https://github.com/openstack/python-glanceclient
* the docs for it...are varied and mostly suck. http://docs.openstack.org/developer/python-glanceclient/ is the official one. But there's also another section in the overall OpenStack CLI documentation: http://docs.openstack.org/cli-reference/content/glanceclient_commands.html . The problem is it's both a library and a client, so the docs treat it oddly in some cases. 
* installing it should be as easy as "pip install python-glanceclient", or install from the git repo

# Cloud Networks:
* You can use the nova client with Cloud Networks extension, which is required for attaching/detaching networks: http://docs.rackspace.com/servers/api/v2/cs-gettingstarted/content/section_gs_install_nova.html
* Optionally the neutron client can be installed but honestly not entirely clear what benefit that gets you: http://docs.rackspace.com/networks/api/v2/cn-gettingstarted/content/install_neutron.html  (install instructions are there, again pip is pretty much the recommendation)

# Cloud Block Storage:
* Primarily accessed via the API, although some things can be specified in nova client (like booting a server from a new or existing volume). So novaclient would be the way if we're talking CLI, but for direct API (cURL) http://docs.rackspace.com/cbs/api/v1.0/cbs-getting-started/content/Sending_requests_with_curl_d1e060.html

# Cloud Files
* The main docs, for reasons unknown to me, recommend the API directly as with CBS. But I've always used, as do many, the Swift client at https://github.com/openstack/python-swiftclient   . Again, can be installed via pip or manually. 
* Official docs at http://docs.openstack.org/developer/python-swiftclient/ but they are code generated docs, so..meh. 
* This should really be bounced off the current Files PM, who I actually don't know. Jose Malacara or Anand would know. 


As far as sending people to the SDK's...I still feel like there are three distinct user groups: direct API consumers (cURL/programmatic), SDK users (actively integrating into another codebase), and CLI users. So, if this is a CLI section, we can keep it clean by focusing on that, but put some general comments about SDK alternative and cURL/native API. 

LMK if this helps!

**Comment by rose-coste** [comment]
copied notes on Cloud Networks, Cloud Images, Cloud Block Storage, to those open issues

new draft, with general startup practices for product-specific CLIs, at http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_interfaces/CLI/setup_CLI.html
