### ISSUE TITLE
Issue with bolding on http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_images_product_concepts/image_properties.html

### ISSUE THREAD

**Issue by annegentle** [rackerlabs/docs-core-infra-user-guide#189]
Trying to describe issue better below.

**Comment by annegentle** [comment]
Now I can't find an example of the definition list problem. Instead the page with an issue is this one

http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud_config/compute/cloud_images_product_concepts/image_properties.html

Source is this:


* **checksum**: the MD5 sum of the image data file

* **status**: the current state of the image. An image must be in
   **active** status in order to be used to boot a server.

* **owner**: indicates who owns the image

* **id**: a universally unique identifier (UUID) assigned to this image

and **active** status is not displaying right.

**Comment by rose-coste** [comment]
addressed by https://github.com/rackerlabs/docs-core-infra-user-guide/commit/92323c49fad052ea20b183d10c4a8702a429a388

extra bolding happens when a multi-line paragraph that starts with bolding isn't all left-aligned. line 2 was one space too far to the right; fixing it got bolding back under control. 

I've fixed a few others like this; seems like anything malformed about the paragraph causes formatting within the paragraph to go wrong. 
Throughout the document, I'm working on handling literals consistently so I changed many **bold** on this page to ``literal``.
