### ISSUE TITLE
blockquote usage on Assumptions page

### ISSUE THREAD

**Issue by ktbartholomew** [rackerlabs/docs-core-infra-user-guide#258]
The assumptions on [this page](https://github.com/rackerlabs/docs-core-infra-user-guide/blob/master/cloud-guide-intro/assumptions.rst) render as a series of `<li>` tags each followed by a `<blockquote>` which doesn't make sense semantically, and doesn't read very well visually. I think it might read better as an actual nested list, and it would be especially helpful if the opening phrases to each item were bold to make the entire page easy to scan.

**Comment by rose-coste** [comment]
with https://github.com/rackerlabs/docs-core-infra-user-guide/pull/260, http://rackspace-core-infra-user-guide.readthedocs.org/en/latest/cloud-guide-intro/assumptions.html combines this feedback & feedback from the editor:

* bold the listitems
* de-italicize the supporting paragraphs

I'm not asking for <blockquote> here but http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#indentation suggests that's what happens when anything is indented. 

I like the appearance of a list of (now bolded) main ideas, each supported by an explanatory paragraph. 

I don't know what you're asking me to do differently. Are you asking to have the explanatory paragraphs left-aligned rather than indented under their listitems?

**Comment by ktbartholomew** [comment]
I can't really think of a scenario where we would want to use the `<blockquote>` tag in our documentation, unless we were directly quoting someone or quoting someone else's documentation. It may seem intuitive to indent something in ReST to visually set it apart, but the fact that it renders as a semantically-incorrect `<blockquote>` means we probably need to find a better pattern for achieving this visual effect.

For now, I think de-indenting each of those paragraphs is probably the best solution.

**Comment by rose-coste** [comment]
https://github.com/rackerlabs/docs-core-infra-user-guide/pull/261 left-aligns the detail paragraphs as requested; closing.
